### ISSUE TITLE
Can not upload template to gorjun with 500MB size

### ISSUE THREAD

**Issue by absidish** [subutai-io/gorjun#150] opened 2017-11-16 08:58 UTC
**reproduce case:**
Tried to upload template (~500MB) to gorjun via Subutai CLI, after wait some time it gives 401 Unauthorized error. 

```
ubuntu@ubuntu:/var/snap/subutai-dev/common/lxc/tmpdir$ sudo subutai export jira -v 0.1 -s medium  -t 8b28d7ec2efdee5c35ddda02e9e6d2dbf6e5eb9f3fdb432184b77b155284xxxx
sudo: unable to resolve host ubuntu
INFO[2017-11-16 06:04:57] jira exported to /var/snap/subutai-dev/common/lxc/tmpdir/jira-subutai-template_0.1_amd64.tar.gz 
ERRO[2017-11-16 07:06:02] Failed to upload template: HTTP status: 401 Unauthorized; Not authorized; 
```
**reason:**
We have 1 hour TTL for token, seems uploading took more than 1 hour, at the end it failes with 401.

**solution:**
we need check token at the start uploading files.

**Comment by marcoarthur** [comment] 2017-11-17 16:42
I'm just blocked to reproduce, since. I still don't know why. Any registered used on my system get a quota of zero ! And so it is impossible to upload operation even begin. This could be only in my local env, since gorjun has a design that change its behavior locally, making impossible to debug parts of code that could be running in deployed gorjun.  I requested @soffokl  help for this, but since is Friday I think we will have to wait till Monday.

**Comment by emli** [comment] 2017-11-18 06:26
Solution is for this issue "we need check token at the start uploading files."  
Regarding to above solution I have debugged the service upload. As result gorjun checks the token at beginning of the upload process. 
In my opinion would be to increase expiration  time of token, because issue creator uploaded a file from his local machine , thus it might take more than an hour to upload a file(500 MB) production hosting

**Comment by emli** [comment] 2017-11-18 06:33
We may need to change authentication  flow for uploading services.

**Comment by akarasulu** [comment] 2017-11-28 13:21
NGINX reverse proxy settings. We are using the proxy_pass module. This does not need to cache. Caching needs to be turned off for both downloads and uploads. The CDN Cache nodes handle this already so we do not need caching for it correct? In this case I suggest testing various settings to disable caching like: (1) use_temp_path=off, (2) expires set to off, (3) setting headers like `add_header 'Cache-Control' 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';` 

First (1) approach is mainly for downloads so I don't think it will help but it cannot hurt to test it.

Second and third approaches probably need to be applied together.

All approaches above ^^^ presume that the NGINX reverse proxy used to front the upstream master Gorjun is not a CDN Cache node. If this presumption is wrong then we have serious issues. I asked the sysadmins if this was the case they told me that the reverse proxy is not a cache node. So turning off caching should be ok. @emli @marcoarthur you guys may want to double, tripple, check this.

**Comment by akarasulu** [comment] 2017-11-28 13:24
Example configuration combining (2) and (3) that you should try. Replace the location regex with the appropriate pattern:

```
location /example {
	add_header 'Cache-Control' 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
	expires off;
}
```

**Comment by Dilshat** [comment] 2017-11-28 13:32
I think out solution is this http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_request_buffering

Also we can change auth scheme for file uploads to avoid changing nginx config later

**Comment by emli** [comment] 2017-11-29 09:02
@akarasulu @Dilshat 

Tested with curl. With false token
1) For small file - returns `Not authorized` immediately
2) For big file - waits and  returns `Not authorized`

For big file it should return `Not authorized` immediately

**Comment by akarasulu** [comment] 2017-11-29 14:00
@emli Please give more information on your test conditions and what are you trying to test. Not clear from your description.

**Comment by emli** [comment] 2017-12-17 14:56
It's gorjun's devops issue.

**Comment by emli** [comment] 2017-12-28 08:24
Since this https://github.com/subutai-io/gorjun/pull/184  solves the bug I'm closing this issue:

**Closed by emli** 2017-12-28 08:24 UTC
Labels: bug, critical
